version: '3'
services:
    zusers:
        build: .
        ports:
            - "8002:8002"
        environment:
            - service=users
        networks:
            - isc
    zposts:
        build: .
        ports:
            - "8001:8001"
        environment:
            - service=posts
        networks:
            - isc
networks:
  isc:
