// Code generated by protoc-gen-go. DO NOT EDIT.
// source: posts/postspb/posts.proto

package postspb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EmptyData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyData) Reset()         { *m = EmptyData{} }
func (m *EmptyData) String() string { return proto.CompactTextString(m) }
func (*EmptyData) ProtoMessage()    {}
func (*EmptyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{0}
}

func (m *EmptyData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyData.Unmarshal(m, b)
}
func (m *EmptyData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyData.Marshal(b, m, deterministic)
}
func (m *EmptyData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyData.Merge(m, src)
}
func (m *EmptyData) XXX_Size() int {
	return xxx_messageInfo_EmptyData.Size(m)
}
func (m *EmptyData) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyData.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyData proto.InternalMessageInfo

type CreatePostRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	AuthorId             int64    `protobuf:"varint,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{1}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreatePostRequest) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type CreatePostResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string   `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Created              int64    `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	AuthorId             int64    `protobuf:"varint,4,opt,name=authorId,proto3" json:"authorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostResponse) Reset()         { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()    {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{2}
}

func (m *CreatePostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostResponse.Unmarshal(m, b)
}
func (m *CreatePostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostResponse.Marshal(b, m, deterministic)
}
func (m *CreatePostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostResponse.Merge(m, src)
}
func (m *CreatePostResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePostResponse.Size(m)
}
func (m *CreatePostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostResponse proto.InternalMessageInfo

func (m *CreatePostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CreatePostResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *CreatePostResponse) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *CreatePostResponse) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type GetPostsResponse struct {
	Posts                []*GetPostsResponse_Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetPostsResponse) Reset()         { *m = GetPostsResponse{} }
func (m *GetPostsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse) ProtoMessage()    {}
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{3}
}

func (m *GetPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse.Unmarshal(m, b)
}
func (m *GetPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse.Merge(m, src)
}
func (m *GetPostsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse.Size(m)
}
func (m *GetPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse proto.InternalMessageInfo

func (m *GetPostsResponse) GetPosts() []*GetPostsResponse_Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type GetPostsResponse_User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostsResponse_User) Reset()         { *m = GetPostsResponse_User{} }
func (m *GetPostsResponse_User) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse_User) ProtoMessage()    {}
func (*GetPostsResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{3, 0}
}

func (m *GetPostsResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse_User.Unmarshal(m, b)
}
func (m *GetPostsResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse_User.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse_User.Merge(m, src)
}
func (m *GetPostsResponse_User) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse_User.Size(m)
}
func (m *GetPostsResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse_User proto.InternalMessageInfo

func (m *GetPostsResponse_User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPostsResponse_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type GetPostsResponse_Post struct {
	Id                   int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Created              int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Author               *GetPostsResponse_User `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetPostsResponse_Post) Reset()         { *m = GetPostsResponse_Post{} }
func (m *GetPostsResponse_Post) String() string { return proto.CompactTextString(m) }
func (*GetPostsResponse_Post) ProtoMessage()    {}
func (*GetPostsResponse_Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{3, 1}
}

func (m *GetPostsResponse_Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostsResponse_Post.Unmarshal(m, b)
}
func (m *GetPostsResponse_Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostsResponse_Post.Marshal(b, m, deterministic)
}
func (m *GetPostsResponse_Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostsResponse_Post.Merge(m, src)
}
func (m *GetPostsResponse_Post) XXX_Size() int {
	return xxx_messageInfo_GetPostsResponse_Post.Size(m)
}
func (m *GetPostsResponse_Post) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostsResponse_Post.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostsResponse_Post proto.InternalMessageInfo

func (m *GetPostsResponse_Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPostsResponse_Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GetPostsResponse_Post) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetPostsResponse_Post) GetAuthor() *GetPostsResponse_User {
	if m != nil {
		return m.Author
	}
	return nil
}

type GetPostRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostRequest) Reset()         { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()    {}
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{4}
}

func (m *GetPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostRequest.Unmarshal(m, b)
}
func (m *GetPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostRequest.Marshal(b, m, deterministic)
}
func (m *GetPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostRequest.Merge(m, src)
}
func (m *GetPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostRequest.Size(m)
}
func (m *GetPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostRequest proto.InternalMessageInfo

func (m *GetPostRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetPostResponse struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Text                 string                `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Created              int64                 `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Author               *GetPostResponse_User `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetPostResponse) Reset()         { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()    {}
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{5}
}

func (m *GetPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse.Unmarshal(m, b)
}
func (m *GetPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse.Marshal(b, m, deterministic)
}
func (m *GetPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse.Merge(m, src)
}
func (m *GetPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse.Size(m)
}
func (m *GetPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse proto.InternalMessageInfo

func (m *GetPostResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPostResponse) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *GetPostResponse) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *GetPostResponse) GetAuthor() *GetPostResponse_User {
	if m != nil {
		return m.Author
	}
	return nil
}

type GetPostResponse_User struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostResponse_User) Reset()         { *m = GetPostResponse_User{} }
func (m *GetPostResponse_User) String() string { return proto.CompactTextString(m) }
func (*GetPostResponse_User) ProtoMessage()    {}
func (*GetPostResponse_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_099164d16d8e72bf, []int{5, 0}
}

func (m *GetPostResponse_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostResponse_User.Unmarshal(m, b)
}
func (m *GetPostResponse_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostResponse_User.Marshal(b, m, deterministic)
}
func (m *GetPostResponse_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostResponse_User.Merge(m, src)
}
func (m *GetPostResponse_User) XXX_Size() int {
	return xxx_messageInfo_GetPostResponse_User.Size(m)
}
func (m *GetPostResponse_User) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostResponse_User.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostResponse_User proto.InternalMessageInfo

func (m *GetPostResponse_User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetPostResponse_User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*EmptyData)(nil), "postspb.EmptyData")
	proto.RegisterType((*CreatePostRequest)(nil), "postspb.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "postspb.CreatePostResponse")
	proto.RegisterType((*GetPostsResponse)(nil), "postspb.GetPostsResponse")
	proto.RegisterType((*GetPostsResponse_User)(nil), "postspb.GetPostsResponse.User")
	proto.RegisterType((*GetPostsResponse_Post)(nil), "postspb.GetPostsResponse.Post")
	proto.RegisterType((*GetPostRequest)(nil), "postspb.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "postspb.GetPostResponse")
	proto.RegisterType((*GetPostResponse_User)(nil), "postspb.GetPostResponse.User")
}

func init() { proto.RegisterFile("posts/postspb/posts.proto", fileDescriptor_099164d16d8e72bf) }

var fileDescriptor_099164d16d8e72bf = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x53, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x6d, 0x9a, 0xd0, 0x8f, 0x2b, 0x2a, 0x70, 0x0b, 0xa9, 0x11, 0xa8, 0xf2, 0xd4, 0x29, 0x48,
	0xe5, 0x63, 0x41, 0x62, 0xa0, 0xa0, 0x8a, 0x0d, 0x05, 0xb1, 0xb0, 0xa5, 0xad, 0x25, 0x3a, 0x34,
	0x09, 0xb1, 0x83, 0x40, 0xe2, 0x97, 0xf1, 0x3b, 0xf8, 0x35, 0x4c, 0x38, 0x8e, 0x63, 0x4a, 0xd2,
	0x32, 0x00, 0x4b, 0x62, 0x9f, 0x9f, 0xef, 0xbd, 0x77, 0xe7, 0x83, 0x5e, 0x1c, 0x71, 0xc1, 0x0f,
	0xd5, 0x37, 0x9e, 0xe4, 0x7f, 0x2f, 0x4e, 0x22, 0x11, 0x61, 0x53, 0x07, 0x69, 0x07, 0xda, 0x57,
	0x8b, 0x58, 0xbc, 0x5c, 0x06, 0x22, 0xa0, 0x23, 0xd8, 0x19, 0x25, 0x2c, 0x10, 0xec, 0x46, 0x9e,
	0xfa, 0xec, 0x31, 0x65, 0x5c, 0x20, 0x82, 0x23, 0xd8, 0xb3, 0x70, 0xad, 0xbe, 0x35, 0x68, 0xfb,
	0x6a, 0x8d, 0x04, 0x5a, 0x41, 0x2a, 0x1e, 0xa2, 0xe4, 0x7a, 0xe6, 0xd6, 0x65, 0xdc, 0xf6, 0xcd,
	0x9e, 0x86, 0x80, 0xcb, 0x49, 0x78, 0x1c, 0x85, 0x9c, 0x61, 0x17, 0xea, 0xf3, 0x99, 0xca, 0x61,
	0xfb, 0x72, 0x65, 0xb2, 0xd6, 0x97, 0xb2, 0xba, 0xd0, 0x9c, 0xaa, 0x9b, 0x33, 0xd7, 0x56, 0xc0,
	0x62, 0xfb, 0x8d, 0xcf, 0x29, 0xf1, 0x7d, 0x58, 0xb0, 0x3d, 0x66, 0x22, 0x63, 0xe3, 0x86, 0xee,
	0x18, 0x36, 0x94, 0x43, 0xc9, 0x68, 0x0f, 0x3a, 0xc3, 0x03, 0x4f, 0xfb, 0xf5, 0xca, 0x48, 0x4f,
	0xa9, 0xcc, 0xc1, 0x64, 0x08, 0xce, 0x1d, 0x67, 0x49, 0x45, 0xac, 0xa4, 0x4f, 0x65, 0x3c, 0x0c,
	0x16, 0x4c, 0x0b, 0x36, 0x7b, 0xf2, 0x0a, 0x4e, 0x96, 0xe2, 0x8f, 0x06, 0x4f, 0xa1, 0x91, 0x1b,
	0x52, 0xf6, 0x7e, 0x14, 0x9c, 0x29, 0xf4, 0x35, 0x9a, 0xf6, 0xa1, 0xab, 0x01, 0x45, 0xbb, 0x4a,
	0x3a, 0xe8, 0x9b, 0x05, 0x5b, 0x06, 0xf2, 0x2f, 0xcd, 0x38, 0x29, 0x69, 0xdd, 0x2f, 0x6b, 0x5d,
	0x29, 0xf5, 0x37, 0xc5, 0x1d, 0xbe, 0x5b, 0xb0, 0xa9, 0xdc, 0xdf, 0xb2, 0xe4, 0x69, 0x3e, 0x65,
	0x38, 0x06, 0xf8, 0x7a, 0x5c, 0x48, 0x0c, 0x73, 0xe5, 0xd9, 0x92, 0xbd, 0x95, 0x67, 0xb9, 0x30,
	0x5a, 0xc3, 0x33, 0x68, 0x15, 0x95, 0x45, 0x34, 0x50, 0x33, 0x0a, 0xa4, 0xb7, 0xb6, 0x01, 0xf2,
	0xf2, 0x39, 0x34, 0x75, 0x14, 0x77, 0xab, 0xe6, 0x73, 0x7e, 0x77, 0x5d, 0x55, 0x68, 0xed, 0xa2,
	0x7d, 0x5f, 0xcc, 0xdf, 0xa4, 0xa1, 0xe6, 0xf1, 0xe8, 0x33, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xeb,
	0x3d, 0x67, 0xac, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PostsServiceClient is the client API for PostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostsServiceClient interface {
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error)
	GetPosts(ctx context.Context, in *EmptyData, opts ...grpc.CallOption) (*GetPostsResponse, error)
	GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error)
}

type postsServiceClient struct {
	cc *grpc.ClientConn
}

func NewPostsServiceClient(cc *grpc.ClientConn) PostsServiceClient {
	return &postsServiceClient{cc}
}

func (c *postsServiceClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*CreatePostResponse, error) {
	out := new(CreatePostResponse)
	err := c.cc.Invoke(ctx, "/postspb.PostsService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPosts(ctx context.Context, in *EmptyData, opts ...grpc.CallOption) (*GetPostsResponse, error) {
	out := new(GetPostsResponse)
	err := c.cc.Invoke(ctx, "/postspb.PostsService/GetPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postsServiceClient) GetPost(ctx context.Context, in *GetPostRequest, opts ...grpc.CallOption) (*GetPostResponse, error) {
	out := new(GetPostResponse)
	err := c.cc.Invoke(ctx, "/postspb.PostsService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostsServiceServer is the server API for PostsService service.
type PostsServiceServer interface {
	CreatePost(context.Context, *CreatePostRequest) (*CreatePostResponse, error)
	GetPosts(context.Context, *EmptyData) (*GetPostsResponse, error)
	GetPost(context.Context, *GetPostRequest) (*GetPostResponse, error)
}

// UnimplementedPostsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostsServiceServer struct {
}

func (*UnimplementedPostsServiceServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*CreatePostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostsServiceServer) GetPosts(ctx context.Context, req *EmptyData) (*GetPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosts not implemented")
}
func (*UnimplementedPostsServiceServer) GetPost(ctx context.Context, req *GetPostRequest) (*GetPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}

func RegisterPostsServiceServer(s *grpc.Server, srv PostsServiceServer) {
	s.RegisterService(&_PostsService_serviceDesc, srv)
}

func _PostsService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postspb.PostsService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postspb.PostsService/GetPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPosts(ctx, req.(*EmptyData))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostsService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostsServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postspb.PostsService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostsServiceServer).GetPost(ctx, req.(*GetPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "postspb.PostsService",
	HandlerType: (*PostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostsService_CreatePost_Handler,
		},
		{
			MethodName: "GetPosts",
			Handler:    _PostsService_GetPosts_Handler,
		},
		{
			MethodName: "GetPost",
			Handler:    _PostsService_GetPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "posts/postspb/posts.proto",
}
